import "./globals.css";
import type { ReactNode } from "react";

export const metadata = {
  title: "Image Project Manage",
  description: "Monitor projects generated by Custom GPT and uploaded through MCP."
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
